# Generated by Django 5.2.5 on 2026-07-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aday_motivasyon_cevabi_alter_takim_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorev',
            name='hedef_katilimci',
            field=models.ForeignKey(blank=True, help_text='Yalnızca Bireysel görev tipinde doldurulur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hedef_gorevler', to='core.katilimci', verbose_name='Hedef Katılımcı'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='hedef_takim',
            field=models.ForeignKey(blank=True, help_text='Yalnızca Takımsal görev tipinde doldurulur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hedef_gorevler', to='core.takim', verbose_name='Hedef Takım'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='gorev_tipi',
            field=models.CharField(choices=[('GENEL', 'Genel'), ('BIREYSEL', 'Bireysel'), ('TAKIMSAL', 'Takımsal')], default='GENEL', max_length=10, verbose_name='Görev Tipi'),
        ),
    ]
