# Generated by Django 5.2.5 on 2026-08-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aday_form_alanlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcerikDNATesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevaplar', models.JSONField(default=dict, verbose_name='Cevaplar')),
                ('rapor_json', models.JSONField(blank=True, default=dict, verbose_name='Rapor JSON')),
                ('rapor_metni', models.TextField(blank=True, verbose_name='Rapor Metni')),
                ('durum', models.CharField(choices=[('TASLAK', 'Taslak'), ('GONDERILDI', 'Gönderildi'), ('ISLENIYOR', 'İşleniyor'), ('TAMAMLANDI', 'Tamamlandı'), ('HATA', 'Hata')], default='TASLAK', max_length=15, verbose_name='Durum')),
                ('hata_mesaji', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='AI Modeli')),
                ('prompt_versiyonu', models.CharField(default='v1', max_length=20, verbose_name='Prompt Versiyonu')),
                ('gonderim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('katilimci', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icerik_dna_testi', to='core.katilimci', verbose_name='Katılımcı')),
            ],
            options={
                'verbose_name': 'İçerik DNA Testi',
                'verbose_name_plural': 'İçerik DNA Testleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
