# Generated by Django 5.2.5 on 2026-07-14 18:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takim_adi', models.CharField(max_length=150, unique=True, verbose_name='Takım Adı')),
                ('mentor', models.CharField(max_length=120, verbose_name='Mentor Adı')),
                ('mentor_eposta', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mentor E-posta')),
                ('buyuk_gorev_basligi', models.CharField(blank=True, help_text="Takımın Demo Day'de sunacağı proje başlığı.", max_length=250, null=True, verbose_name='Büyük Görev Proje Başlığı')),
                ('toplam_puan', models.PositiveIntegerField(default=0, verbose_name='Toplam Puan')),
                ('olusturulma_tarihi', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
                'ordering': ['-toplam_puan', 'takim_adi'],
            },
        ),
        migrations.CreateModel(
            name='Aday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('eposta', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('telefon', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefon numarası +905XXXXXXXXX veya 05XXXXXXXXX formatında olmalıdır.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon')),
                ('universite', models.CharField(max_length=200, verbose_name='Üniversite')),
                ('bolum', models.CharField(max_length=150, verbose_name='Bölüm')),
                ('sehir', models.CharField(max_length=100, verbose_name='Şehir')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('instagram', models.CharField(blank=True, max_length=60, null=True, verbose_name='Instagram (@kullanıcı)')),
                ('twitter', models.CharField(blank=True, max_length=60, null=True, verbose_name='Twitter/X (@kullanıcı)')),
                ('motivasyon_cevabi', models.TextField(help_text='Bu programa neden katılmak istiyorsunuz?', verbose_name='Motivasyon Cevabı')),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('basvuru_durumu', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLIYOR', max_length=20, verbose_name='Başvuru Durumu')),
            ],
            options={
                'verbose_name': 'Aday',
                'verbose_name_plural': 'Adaylar',
                'ordering': ['-basvuru_tarihi'],
                'indexes': [models.Index(fields=['eposta'], name='core_aday_eposta_192c3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hafta', models.PositiveSmallIntegerField(verbose_name='Hafta No')),
                ('gorev_adi', models.CharField(max_length=200, verbose_name='Görev Adı')),
                ('brief_aciklama', models.TextField(verbose_name='Brief Açıklaması')),
                ('gorev_tipi', models.CharField(choices=[('BIREYSEL', 'Bireysel'), ('TAKIM', 'Takım')], default='TAKIM', max_length=10, verbose_name='Görev Tipi')),
                ('son_teslim_tarihi', models.DateTimeField(verbose_name='Son Teslim Tarihi')),
                ('puan_kriterleri', models.TextField(help_text='Her kriter için puan aralığını açıklayın (örn: Yenilikçilik: 0-30 puan).', verbose_name='Puan Kriterleri')),
                ('maksimum_puan', models.PositiveSmallIntegerField(default=100, verbose_name='Maksimum Puan')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['hafta', 'gorev_adi'],
                'unique_together': {('hafta', 'gorev_adi')},
            },
        ),
        migrations.CreateModel(
            name='Katilimci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabul_durumu', models.BooleanField(default=False, verbose_name='Kabul Edildi mi?')),
                ('kabul_tarihi', models.DateField(blank=True, null=True, verbose_name='Kabul Tarihi')),
                ('program_katilim_durumu', models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif (Devamsız)'), ('MEZUN', 'Mezun'), ('AYRILDI', 'Ayrıldı')], default='AKTIF', max_length=20, verbose_name='Program Katılım Durumu')),
                ('notlar', models.TextField(blank=True, help_text='Mentör/yönetici tarafından görülebilir iç notlar.', verbose_name='Yönetici Notları')),
                ('aday', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='katilimci', to='core.aday', verbose_name='Aday')),
                ('takim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='katilimcilar', to='core.takim', verbose_name='Takım')),
            ],
            options={
                'verbose_name': 'Katılımcı',
                'verbose_name_plural': 'Katılımcılar',
                'ordering': ['aday__ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='Teslim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teslim_linki', models.URLField(verbose_name='Teslim Linki (GitHub / Drive / vb.)')),
                ('teslim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Teslim Tarihi')),
                ('aciklama', models.TextField(blank=True, help_text='Katılımcının teslim hakkındaki notları.', verbose_name='Katılımcı Açıklaması')),
                ('mentor_yorumu', models.TextField(blank=True, verbose_name='Mentor Yorumu')),
                ('alinan_puan', models.PositiveSmallIntegerField(default=0, verbose_name='Alınan Puan')),
                ('degerlendirildi', models.BooleanField(default=False, verbose_name='Değerlendirildi mi?')),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teslimler', to='core.gorev', verbose_name='Görev')),
                ('katilimci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teslimler', to='core.katilimci', verbose_name='Katılımcı')),
                ('takim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teslimler', to='core.takim', verbose_name='Takım')),
            ],
            options={
                'verbose_name': 'Teslim',
                'verbose_name_plural': 'Teslimler',
                'ordering': ['-teslim_tarihi'],
            },
        ),
    ]
