# Generated by Django 5.2.5 on 2026-07-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aday',
            name='motivasyon_cevabi',
            field=models.TextField(blank=True, help_text='Bu programa neden katılmak istiyorsunuz?', null=True, verbose_name='Motivasyon Cevabı'),
        ),
        migrations.AlterField(
            model_name='takim',
            name='mentor',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Mentor Adı'),
        ),
        migrations.AlterField(
            model_name='teslim',
            name='alinan_puan',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Alınan Puan'),
        ),
        migrations.AlterField(
            model_name='teslim',
            name='mentor_yorumu',
            field=models.TextField(blank=True, null=True, verbose_name='Mentor Yorumu'),
        ),
    ]
