# Generated by Django 5.2.5 on 2026-07-16 18:25

import django.db.models.deletion
from django.db import migrations, models


def clear_old_mentor_text(apps, schema_editor):
    """
    Eski düz metin mentor değerlerini NULL'a sıfırla.
    (AlterField ile FK'ya dönüşmeden önce çalışır)
    """
    # Ham SQL ile güncelle — model sınıfları henüz geçiş durumunda
    schema_editor.execute("UPDATE core_takim SET mentor = NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gorev_hedef_katilimci_gorev_hedef_takim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('eposta', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('uzmanlik', models.CharField(blank=True, help_text='Örn: Dijital Sağlık Pazarlaması, Ürün Tasarımı', max_length=200, verbose_name='Uzmanlık Alanı')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentorlar',
                'ordering': ['ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adi', models.CharField(max_length=200, verbose_name='Şirket Adı')),
                ('yetkili', models.CharField(max_length=150, verbose_name='Yetkili Kişi')),
                ('eposta', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsorlar',
                'ordering': ['sirket_adi'],
            },
        ),
        migrations.RemoveField(
            model_name='takim',
            name='mentor_eposta',
        ),
        # Eski düz metin mentor verilerini NULL'a sıfırla (FK'ya geçmeden önce zorunlu)
        migrations.RunPython(clear_old_mentor_text, migrations.RunPython.noop),
        migrations.AddField(
            model_name='teslim',
            name='revizyon_istendi',
            field=models.BooleanField(default=False, verbose_name='Revizyon İstendi mi?'),
        ),
        migrations.AlterField(
            model_name='takim',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takimlar', to='core.mentor', verbose_name='Mentor'),
        ),
    ]
