# Generated by Django 5.2.5 on 2026-07-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_katilimci_user_mentor_user_sponsor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslim',
            name='teslim_linki',
            field=models.URLField(blank=True, null=True, verbose_name='Teslim Linki (GitHub / Drive / vb.)'),
        ),
    ]
