# Generated by Django 5.2.5 on 2026-07-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_teslim_teslim_linki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
