# Generated by Django 5.2.5 on 2026-07-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_sponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katilimci',
            options={'ordering': ['aday__ad'], 'verbose_name': 'Katılımcı', 'verbose_name_plural': 'Katılımcılar'},
        ),
        migrations.RemoveField(
            model_name='aday',
            name='ad_soyad',
        ),
        migrations.RemoveField(
            model_name='aday',
            name='bolum',
        ),
        migrations.RemoveField(
            model_name='aday',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='aday',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='aday',
            name='motivasyon_cevabi',
        ),
        migrations.RemoveField(
            model_name='aday',
            name='sehir',
        ),
        migrations.RemoveField(
            model_name='aday',
            name='twitter',
        ),
        migrations.AddField(
            model_name='aday',
            name='ad',
            field=models.CharField(default='', max_length=80, verbose_name='Ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aday',
            name='icerik_uretimi',
            field=models.TextField(blank=True, null=True, verbose_name='Icerik Uretim Deneyimi'),
        ),
        migrations.AddField(
            model_name='aday',
            name='kaynak',
            field=models.CharField(default='Google Form', max_length=50, verbose_name='Basvuru Kaynagi'),
        ),
        migrations.AddField(
            model_name='aday',
            name='sinif',
            field=models.CharField(blank=True, choices=[('1. Sinif', '1. Sinif'), ('2. Sinif', '2. Sinif'), ('3. Sinif', '3. Sinif'), ('4. Sinif', '4. Sinif'), ('Mezun', 'Mezun'), ('Diger', 'Diger')], max_length=20, null=True, verbose_name='Sinif'),
        ),
        migrations.AddField(
            model_name='aday',
            name='sosyal_medya',
            field=models.TextField(blank=True, null=True, verbose_name='Sosyal Medya Adresleri'),
        ),
        migrations.AddField(
            model_name='aday',
            name='soyad',
            field=models.CharField(default='', max_length=80, verbose_name='Soyad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aday',
            name='takvim_onay',
            field=models.BooleanField(default=False, verbose_name='Program Takvimine Uyum Onayi'),
        ),
        migrations.AlterField(
            model_name='aday',
            name='basvuru_durumu',
            field=models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ONAYLANDI', 'Onaylandi'), ('REDDEDILDI', 'Reddedildi')], default='BEKLIYOR', max_length=20, verbose_name='Basvuru Durumu'),
        ),
        migrations.AlterField(
            model_name='aday',
            name='basvuru_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Basvuru Tarihi'),
        ),
        migrations.AlterField(
            model_name='aday',
            name='telefon',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='aday',
            name='universite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Universite'),
        ),
    ]
