# Generated by Django 5.2.5 on 2026-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_icerikdnatesti'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslim',
            name='teslim_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to='teslimler/', verbose_name='Teslim Dosyası'),
        ),
    ]
