# Generated by Django 5.2.5 on 2026-08-02 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_teslim_teslim_dosyasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teslim',
            name='durum',
            field=models.CharField(choices=[('BEKLIYOR', 'Değerlendirme Bekliyor'), ('REVIZYON_ISTENDI', 'Revizyon İstendi'), ('REVIZE_EDILDI', 'Revize Edildi'), ('TAMAMLANDI', 'Değerlendirme Tamamlandı')], default='BEKLIYOR', max_length=20, verbose_name='Teslim Durumu'),
        ),
        migrations.CreateModel(
            name='TeslimHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(choices=[('ILK_TESLIM', 'İlk Teslim'), ('REVIZYON_ISTENDI', 'Revizyon İstendi'), ('REVIZE_TESLIM', 'Revize Teslim'), ('NIHAI_DEGERLENDIRME', 'Nihai Değerlendirme')], max_length=25, verbose_name='İşlem Tipi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('teslim_linki', models.URLField(blank=True, null=True, verbose_name='Teslim Linki')),
                ('teslim_dosyasi', models.FileField(blank=True, null=True, upload_to='teslimler/hareketler/', verbose_name='Teslim Dosyası')),
                ('puan', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puan')),
                ('mentor_yorumu', models.TextField(blank=True, null=True, verbose_name='Mentor Yorumu')),
                ('revizyon_notu', models.TextField(blank=True, null=True, verbose_name='Revizyon Notu')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('olusturan_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('teslim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='core.teslim', verbose_name='Teslim')),
            ],
            options={
                'verbose_name': 'Teslim Hareketi',
                'verbose_name_plural': 'Teslim Hareketleri',
                'ordering': ['olusturulma_tarihi'],
            },
        ),
    ]
