# Generated by Django 5.2.5 on 2026-08-05 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teslim_durum_teslimhareketi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformansKriteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Ad')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('kategori', models.CharField(choices=[('GOREV', 'Görev'), ('KATILIM', 'Katılım'), ('ETKILESIM', 'Etkileşim'), ('MANUEL', 'Manuel')], default='MANUEL', max_length=10, verbose_name='Kategori')),
                ('maksimum_puan', models.PositiveIntegerField(default=100, verbose_name='Maksimum Puan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Performans Kriteri',
                'verbose_name_plural': 'Performans Kriterleri',
                'ordering': ['kategori', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='KatilimciPerformans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bireysel_puan', models.PositiveIntegerField(default=0, verbose_name='Bireysel Puan')),
                ('gorev_puani', models.PositiveIntegerField(default=0, verbose_name='Görev Puanı')),
                ('toplanti_katilim_puani', models.PositiveIntegerField(default=0, verbose_name='Toplantı Katılım Puanı')),
                ('etkilesim_bonus_puani', models.PositiveIntegerField(default=0, verbose_name='Etkileşim Bonus Puanı')),
                ('manuel_puan', models.IntegerField(default=0, verbose_name='Manuel Puan')),
                ('admin_ici_not', models.TextField(blank=True, verbose_name='Admin İçi Not')),
                ('katilimciya_gorunen_not', models.TextField(blank=True, verbose_name='Katılımcıya Görünen Not')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('katilimci', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performans', to='core.katilimci', verbose_name='Katılımcı')),
            ],
            options={
                'verbose_name': 'Katılımcı Performans',
                'verbose_name_plural': 'Katılımcı Performansları',
            },
        ),
        migrations.CreateModel(
            name='KatilimciPerformansNotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField(default=0, verbose_name='Puan')),
                ('not_metni', models.TextField(blank=True, verbose_name='Not Metni')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('katilimci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performans_notlari', to='core.katilimci', verbose_name='Katılımcı')),
                ('veren_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verdigi_performans_notlari', to=settings.AUTH_USER_MODEL, verbose_name='Notu Veren Kullanıcı')),
                ('kriter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notlar', to='core.performanskriteri', verbose_name='Kriter')),
            ],
            options={
                'verbose_name': 'Katılımcı Performans Notu',
                'verbose_name_plural': 'Katılımcı Performans Notları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SosyalMedyaPerformansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100, verbose_name='Platform')),
                ('takipci_sayisi', models.PositiveIntegerField(default=0, verbose_name='Takipçi Sayısı')),
                ('etkilesim_sayisi', models.PositiveIntegerField(default=0, verbose_name='Etkileşim Sayısı')),
                ('etkilesim_orani', models.FloatField(default=0.0, verbose_name='Etkileşim Oranı (%)')),
                ('bonus_puan', models.PositiveIntegerField(default=0, verbose_name='Bonus Puan')),
                ('not_metni', models.TextField(blank=True, verbose_name='Not')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('giren_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='girdigi_sosyal_medya_performanslari', to=settings.AUTH_USER_MODEL, verbose_name='Girişi Yapan Kullanıcı')),
                ('katilimci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sosyal_medya_performanslari', to='core.katilimci', verbose_name='Katılımcı')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Performansı',
                'verbose_name_plural': 'Sosyal Medya Performansları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='ToplantiKatilimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=250, verbose_name='Toplantı Başlığı')),
                ('tarih', models.DateField(verbose_name='Toplantı Tarihi')),
                ('katildi_mi', models.BooleanField(default=False, verbose_name='Katıldı mı?')),
                ('katilim_puani', models.PositiveIntegerField(default=0, verbose_name='Katılım Puanı')),
                ('not_metni', models.TextField(blank=True, verbose_name='Not')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('giren_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='girdigi_toplanti_katilimlari', to=settings.AUTH_USER_MODEL, verbose_name='Girişi Yapan Kullanıcı')),
                ('katilimci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplanti_katilimlari', to='core.katilimci', verbose_name='Katılımcı')),
            ],
            options={
                'verbose_name': 'Toplantı Katılımı',
                'verbose_name_plural': 'Toplantı Katılımları',
                'ordering': ['-tarih'],
            },
        ),
    ]
